### Get Token
POST http://localhost:8080/realms/my-project/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=backend-client&
client_secret=AoNDt1Z4UeM4JRbisXMsxxBppf4jg6hu&
grant_type=password&
username=useradmin&
password=admin


> {%
    client.global.set("authToken", response.body.access_token);
%}

###
GET http://127.0.0.1:8888/api/v1/cvs/reportTemplates?page=0&size=20&sort=reportId,desc
Authorization: Bearer {{authToken}}
###

GET http://127.0.0.1:8888/api/v1/cvs/report?page=0&size=20&sort=id,desc
Authorization: Bearer {{authToken}}
###

POST  http://127.0.0.1:8888/api/v1/cvs/report
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "reportId": 1,
  "userEmail": "ksanka82@yandex.ru",
  "rangeStart": "2023-01-01",
  "rangeEnd": "2023-12-01"
}



###











