server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: EMAIL-NOTIFICATION-SERVICE
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  mail:
    host: smtp.yandex.ru
    port: 587
    username: ${USER_NAME}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
      group-id: email-events
      properties:
        spring-json-trusted-packages: by.javaguru.core
        request.timeout.ms: 60000
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000
        max.poll.interval.ms: 300000
      isolation-level: read_committed
      auto-offset-reset: earliest

